eureka:
  instance:
    hostname: eurekaServer.com
  client:
    register-with-eureka: false #自己不注册进服务列表中
    fetch-registry: false #不通过Eureka获取注册信息
    service-url:
      defaultZone: http://localhost:8011/eureka/
