logging:
  level:
    console: DEBUG
    service: INFO

spring:
  main:
    #esayPoi解决beanNameViewResolver报错的问题
    allow-bean-definition-overriding: true

  datasource:
    url: jdbc:mysql://localhost:3306/customer?useUnicode=true&characterEncoding=UTF-8&zeroDateTimeBehavior=convertToNull&allowMultiQueries=true
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 1234
    druid:
      # 下面为连接池的补充设置，应用到上面所有数据源中
      # 初始化大小，最小，最大
      initial-size: 10                    #连接池初始大小
      max-active: 20                      #连接池中最大的活跃连接数
      min-idle: 5                         #连接池中最小的活跃连接数
      max-wait: 60000                     #配置获取连接等待超时的时间
      # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
      time-between-eviction-runs-millis: 600000
      # 配置一个连接在池中最小生存的时间，单位是毫秒
      min-evictable-idle-time-millis: 300000
      validation-query: SELECT 1 FROM DUAL
      test-on-borrow: false             #是否在获得连接后检测其可用性
      test-on-return: false             #是否在连接放回连接池后检测其可用性
      test-while-idle: true             #是否在连接空闲一段时间后检测其可用性
      pool-prepared-statements: true    #打开PSCache，并且指定每个连接上PSCache的大小
      max-pool-prepared-statement-per-connection-size: 20
      # 配置监控统计拦截的filters
      filters: stat,wall
      use-global-data-source-stat: true

  devtools:
    restart:
      enabled: true #开启热部署，重新编译后即可实现热部署

  redis:
    #  Redis默认情况下有16个分片，这里配置具体使用的分片，默认是0
    database: 0
    host: 127.0.0.1
    timeout: 10000ms
    port: 6379
    lettuce:
      pool:
        # 连接池最大连接数（使用负值表示没有限制） 默认 8
        max-active: 16
        # 连接池中的最大空闲连接 默认 8
        max-idle: 8
        # 连接池中的最小空闲连接 默认 0
        min-idle: 0
        # 连接池最大阻塞等待时间（使用负值表示没有限制） 默认 -1
        max-wait: -1ms
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8011/eureka/
  instance:
    ip-address: true

# 在配置文件中配置tomcat的临时目录
server:
  tomcat:
    basedir: /home/temp




